services:
  # Go Backend Service
  go-backend:
    build:
      context: ./go-backend
      dockerfile: Dockerfile
    volumes:
      - ${ROOT_PATH:-./data}:/app/static:rw
    environment:
      - ROOT_PATH=/app/static
      - PORT=8080
      - NEXT_PUBLIC_BASE_URL=http://localhost:2929
    expose:
      - "8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Next.js Frontend Service
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-http://localhost:2929}
      - NEXT_PUBLIC_GO_API_URL=${NEXT_PUBLIC_GO_API_URL:-}
    expose:
      - "3000"
    depends_on:
      - go-backend
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:stable-alpine
    ports:
      - "${PORT:-2929}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${ROOT_PATH:-./data}:/app/static:ro
    depends_on:
      - nextjs
      - go-backend
    restart: unless-stopped
