services:
  # Use prebuilt binaries and Next.js standalone output committed in the repo
  go-backend:
    image: alpine:3.20
    working_dir: /app
    environment:
      - ROOT_PATH=/app/static
      - PORT=9932
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-http://localhost:2929}
    volumes:
      - ${ROOT_PATH:-./data}:/app/static:rw
      # Prebuilt backend binaries (amd64 and arm64); the container picks at runtime
      - ./backend/nextbrowse-backend:/app/main:ro
      - ./backend/backend_arm64:/app/main_arm64:ro
    expose:
      - "9932"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:9932/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command:
      - /bin/sh
      - -c
      - >-
        apk add --no-cache ca-certificates wget >/dev/null 2>&1;
        ARCH=$(uname -m);
        if [ "$ARCH" = aarch64 ] || [ "$ARCH" = arm64 ]; then
          chmod +x /app/main_arm64 && exec /app/main_arm64;
        else
          chmod +x /app/main && exec /app/main;
        fi

  nextjs:
    image: node:20-bookworm-slim
    working_dir: /app
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-http://localhost:2929}
      - NEXT_PUBLIC_GO_API_URL=${NEXT_PUBLIC_GO_API_URL:-}
    # Run with standalone Next.js server from prebuilt artifacts
    volumes:
      - ./frontend/.next/standalone:/app:ro
      - ./frontend/.next/static:/app/.next/static:ro
      - ./frontend/public:/app/public:ro
      - ${ROOT_PATH:-./data}:/app/static:rw
    expose:
      - "3000"
    command: ["node", "server.js"]
    depends_on:
      - go-backend
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - "${PORT:-2929}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${ROOT_PATH:-./data}:/app/static:rw
    depends_on:
      - nextjs
      - go-backend
    restart: unless-stopped
