services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${ROOT_PATH:-./data}:/app/static:rw
    environment:
      - NODE_ENV=production
      - ROOT_DIR=/app/static
      - NEXT_PUBLIC_BASE_URL=http://localhost:2929
    expose:
      - "3000"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - "${PORT:-2929}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${ROOT_PATH:-./data}:/app/static:ro
    depends_on:
      - nextjs
    restart: unless-stopped
